"use strict";
/**
 * Created by rocky on 17/2/17.
 */

exports.os= {
    windows: "Windows.",
    macosx: "Macintosh.",
    ios: "iOS.",
    android: "Android.",
    chromeos: "Chrome OS.",
    linux: "Linux.",
    wp: "Windows Phone.",
    windowsce: "Windows CE, include Windows Mobile, Smartphone, PPC.",
    symbian: "Symbian OS.",
    blackberry: "Blackberry OS.",
    yunos: "Aliyun OS."
}

exports.device = {
    pc: "Windows PC.",
    mac: "Macintosh PC.",
    iphone: "iPhone.",
    ipad: "iPad.",
    ipod: "iPod.",
    android: "Android.",
    blackberry: "Blackberry mobile.",
    wp: "Windows Phone.",
    mi: "Xiaomi.",
    meizu: "meizu.",
    nexus: "Nexus.",
    nokia: "Nokia.",
    samsung: "samsung.",
    aliyun: "Aliyun.",
    huawei: "Huawei （华为）",
    lenovo: "lenovo.",
    zte: "ZTE Corporation （中兴）",
    vivo: "vivo （步步高）",
    htc: "HTC.",
    oppo: "OPPO.",
    "konka": "konka （康佳）",
    sonyericsson: "sonyericsson （索尼爱立信）",
    coolpad: "coolpad （酷派）",
    lg: "LG.",
    noain: "诺亚信",
    "huawei-honor": "华为荣耀",
    lephone: "乐 Phone",
    asus: "华硕",
    alcatel: "alcatel",
    "一加" :"一加",
    "蓝米": "蓝米",
    "E 派": "E 派",
    "hike": "hike",
    "qmi": "qmi",
    "友信达": "友信达",
    "优米": "优米",
    "嘉源": "嘉源",
    "intki": "intki",
    "星语": "星语",
    "欧奇": "欧奇",
    "海派": "海派",
    "广信": "广信",
    nibiru: "nibiru",
    "神州":"神州",
    "青橙":"青橙",
    "海信":"海信",
    "金立":"金立",
    "eton":"eton",
    "bohp":"bohp",
    "小杨树":"小杨树",
    "语信":"语信",
    "nubia":"nubia",
    "爱讯达":"爱讯达",
    "寰宇通":"寰宇通",
    "mofut":"mofut",
    "infocus":"infocus",
    "大唐":"大唐",
    "邦华":"邦华",
    "天迈":"天迈",
    "大显":"大显",
    "博瑞":"博瑞",
    "lingwin":"lingwin",
    "iusai":"iusai",
    "波导":"波导",
    "德赛":"德赛",
    "蓝魔":"蓝魔",
    "美图":"美图",
    "opsson":"opsson",
    "benwee":"benwee",
    "hosin":"hosin",
    "smartisan":"锤子, Smartisan.",
    "ephone":"ephone",
    "佰事讯":"佰事讯",
    "newman":"newman",
    "haier":"haier",
    "moto":"moto",
    "tcl":"tcl",
    "天语":"天语",
    "doov":"doov",
    "天时达":"天时达",
}
exports.browser = {
    na : "unknown browser",
    edge: "Microsoft Edge browser.",
    ie: "Microsoft Internet Explorer.",
    chrome: "Google Chrome.",
    firefox: "Mozilla Firefox.",
    safari: "Apple Safari.",
    opera: "Opera.",
    360: "Qihu 360 browser.",
    maxthon: "Maxthon.",
    sogou: "Sogou.",
    theworld: "TheWorld.",
    green: "GreenBrowser.",
    qq: "QQ Browser.",
    tt: "TencentTraveler.",
    liebao: "Cheetah Mobile Inc. （猎豹） Browser.",
    tao: "Taobao （淘宝） Browser.",
    coolnovo: "coolnovo （枫树）",
    saayaa: "Saayaa （闪游）",
    uc: "UC Browser.",
    mi: "Build-in browser in Xiaomi （小米）.",
    baidu: "Baidu （百度） browser.",
    nokia: "Build-in Browser in Nokia （诺基亚）",
    blackberry: "黑莓默认浏览器，版本号与系统版本相同。",
    webview: "iOS WebView.",
    yandex: "Yandex YaBrowser.",
    micromessenger: "WeChat （微信）",
    "ali-ap": "支付宝手机钱包。",
    "ali-ap-pd": "支付宝平板客户端。",
    "ali-am": "支付宝商户客户端。",
    "ali-tb": "淘宝手机客户端。",
    "ali-tb-pd": "淘宝平板客户端。",
    "ali-tm": "天猫手机客户端。",
    "ali-tm-pd": "天猫平板客户端。",
    //机器人
    googlebot: "Googlebot",
    baiduspider: "Baiduspider ，百度无线、网页搜索",
    "baiduspider-image": "百度图片搜索",
    "baiduspider-video": "百度视频搜索",
    "baiduspider-news": "百度新闻搜索",
    "baiduspider-favo": "百度收藏搜索",
    "baiduspider-cpro": "百度联盟",
    "baiduspider-ads": "百度商务搜索",
    baiduboxapp: "百度手机搜索客户端",
    bingbot: "Bingbot 网络爬虫。",
    msnbot: "MSNBot",
    nuhkbot: "Nuhkbot",
    alexabot: "Alexabot.",
    curl: "curl."
};
